site_name: COMP423 Course Notes
theme:
  name: material

  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select

  markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences