site_name: COMP423 Course Notes
theme:
  name: material

  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select

  markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.betterem
    - admonition
    - attr_list
    - md_in_html